config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"
  get "/changepassword" => "users#changepassword", as: :changepassword_user
  get "/manageusers" => "users#manage_users", as: :manage_users
  get "/users/:id/email" => "users#email", as: :email_user
  get "/users/:id/role" => "users#role", as: :role_user
  get "/users/:id/change_password" => "users#change_password", as: :change_password

  get "menu_categories/:id/add_item" => "menu_categories#add_item", as: :add_item
  get "menu_items/:id/flip_status" => "menu_items#flip_status", as: :flip_status

  get "cart_items/:id/plus" => "cart_items#plus", as: :plus
  get "cart_items/:id/minus" => "cart_items#minus", as: :minus

  get "orders/:id/edit" => "orders#edit", as: :edit

  #get "/updatemenus" => "menu_categories#update_menus", as: :update_menus
  get "/managemenus" => "menu_categories#manage_menus", as: :manage_menus

  resources :users, :orders, :order_items, :menu_categories, :menu_items
  resources :carts, :cart_items

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe Reedhi's Manager App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="HomeBanner-div">
      <p class="HomeBanner-title">
          <%= link_to "Home", "/", method: "GET" %>
      </p>

      <% if @current_user %>
        <% if @current_user.role == "owner" %>
          <p class="HomeHeader-title"> <%= link_to "Manage Users", manage_users_path %> </p>
          <p class="HomeHeader-title"> <%= link_to "Manage Menus", menu_categories_path %></p>
        <% else %>
          <p class="HomeHeader-title">
            <%= link_to "Change Password", "/changepassword", method: "GET" %>
          </p>
        <% end %>
        <div class="HomeBanner-div">
          <p> <%= @current_user.name %>(<%= @current_user.role %>):
           <% user_orders = Order.of_user(@current_user.id)%>
          <% if @current_user.role != "customer" %>
              <%= link_to Order.all.count, orders_path, method: "GET" %>
          <% else %>
            <% if !user_orders.empty? %>
              <%= link_to user_orders.order_count(@current_user.id), orders_path, method: "GET" %>
            <% else %>
              <%= link_to user_orders.order_count(@current_user.id), orders_path, method: "GET" %>
            <% end %>
          <% end %>
          Orders: Pending:
          <% if @current_user.role != "customer" %>
            <%= link_to Order.pending, orders_path, method: "GET" %>
          <% else %>
            <%# if !user_orders.empty?) %>
              <%= link_to (Order.pending_of_user(@current_user.id)), orders_path, method: "GET" %> </p>
            <%# end %>
          <% end %>
          <% user_cart = Cart.of_user(@current_user.id) %>
        <% if user_cart %>
          <% if CartItem.of_cart_id(user_cart.id).count != 0 %>
              <p> / Cart Items: <%= link_to CartItem.of_cart_id(user_cart.id).count, orders_path, method: "GET" %> </p>
          <% end %>
        <% end %>
        </div>
          <p> <%= link_to "Sign-out", destroy_session_path, method: "delete" %> </p>
    </div>
    <div class="HomeHeader-div">
        <p class="HomeHeader-message"> Welcome to Cafe Reedhi's Services. </p>
      <% else %>
        <p class="HomeHeader-message">Hello Friend ! Welcome to Cafe Reedhi's Services.
              Please <%= link_to "Sign-in", new_sessions_path, method: "get" %>
              to help us serve you better.
        </p>
        <p class="HomeBanner-title">New User <%= link_to "Sign-Up", new_user_path %> </p>
      <% end %>
    </div>
    <p class="Flash-message">
        <%= flash[:error] %>
    </p>
    <%= yield %>
    <div>
    <h3 style="background-color:lightgreen;color:blue;
                text-align:center;margin-top:10px;">
        Copy-right@reedhi durgapur
    </h3>
    </div>
  </body>
</html>